'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import Sidebar from '../components/Sidebar'
import Navbar from '../components/Navbar'
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    return (
        <html lang="en">
            <body>
                <div className="app">
                    <Sidebar />
                    <div className="container__wide w-full">
                        <Navbar />
                        <div className="p-3">{children}</div>
                    </div>
                </div>
                <Script src="flowbite/dist/flowbite.min.js"></Script>
            </body>
        </html>
    )
}
